private ["_obj","_pos","_para","_itemData"];
closeDialog 0 ;
storePurchaseHandle = nil;
_itemData = _this select 0;
switch (_itemData) do {
    case "basecore": {[0]call createBasecore;
    };
    case "lootbox": {call createLootBox;
    };
    case "nuclear": {call startNuclearStrike;
    };
    case "artillery": {[_itemData, 1] call mf_inventory_add;
    };
    case "water": {[_itemData, 1] call mf_inventory_add;
    };
    case "cannedfood": {[_itemData, 1] call mf_inventory_add;
    };
    case "repairkit": {[_itemData, 1] call mf_inventory_add;
    };
    case "jerrycanfull": {[_itemData, 1] call mf_inventory_add;
    };
    case "jerrycanempty": {[_itemData, 1] call mf_inventory_add;
    };
    case "spawnbeacon": {[_itemData, 1] call mf_inventory_add;
    };
    case "camonet": {[_itemData, 1] call mf_inventory_add;
    };
    case "syphonhose": {[_itemData, 1] call mf_inventory_add;
    };
    case "energydrink": {[_itemData, 1] call mf_inventory_add;
    };
    case "warchest": {[_itemData, 1] call mf_inventory_add;
    };
    case "Rabbit_F": {[_itemData] spawn becomeAnimal;
    };
    case "Salema_F": {[_itemData] spawn becomeAnimal;
    };
    case "Ornate_random_F": {[_itemData] spawn becomeAnimal;
    };
    case "Mackerel_F": {[_itemData] spawn becomeAnimal;
    };
    case "Tuna_F": {[_itemData] spawn becomeAnimal;
    };
    case "Mullet_F": {[_itemData] spawn becomeAnimal;
    };
    case "CatShark_F": {[_itemData] spawn becomeAnimal;
    };
    case "Snake_random_F": {[_itemData] spawn becomeAnimal;
    };
    case "Turtle_F": {[_itemData] spawn becomeAnimal;
    };
    case "Cock_random_F": {[_itemData] spawn becomeAnimal;
    };
    case "Cock_white_F": {[_itemData] spawn becomeAnimal;
    };
    case "Fin_sand_F": {[_itemData] spawn becomeAnimal;
    };
    case "Fin_blackwhite_F": {[_itemData] spawn becomeAnimal;
    };
    case "Fin_ocherwhite_F": {[_itemData] spawn becomeAnimal;
    };
    case "Fin_tricolour_F": {[_itemData] spawn becomeAnimal;
    };
    case "Fin_random_F": {[_itemData] spawn becomeAnimal;
    };
    case "Alsatian_Sand_F": {[_itemData] spawn becomeAnimal;
    };
    case "Alsatian_Black_F": {[_itemData] spawn becomeAnimal;
    };
    case "Alsatian_Sandblack_F": {[_itemData] spawn becomeAnimal;
    };
    case "Alsatian_Random_F": {[_itemData] spawn becomeAnimal;
    };
    case "Goat_random_F": {[_itemData] spawn becomeAnimal;
    };
    case "Sheep_random_F": {[_itemData] spawn becomeAnimal;
    };

};