/****** TOW WITH VEHICLE  ******/

/**
 * List of class names of vehicles which can tow towables objects.
 */
R3F_LOG_CFG_remorqueurs =
[
	"C_Kart_01_F",
"C_Tractor_01_F",
"I_G_Quadbike_01_F",
"C_Hatchback_01_sport_F",
"C_SUV_01_F",
"C_Offroad_02_unarmed_F",
"C_Offroad_01_F",
"I_G_Offroad_01_F",
"B_GEN_Offroad_01_gen_F",
"C_Van_01_transport_F",
"C_Van_01_fuel_F",
"C_Van_02_vehicle_F",
"C_Van_02_transport_F",
"B_GEN_Van_02_transport_F",
"C_Van_02_service_F",
"O_Truck_03_device_F",
"O_Truck_03_medical_F",
"O_Truck_03_repair_F",
"I_Truck_02_ammo_F",
"I_Truck_02_medical_F",
"B_UGV_01_F",
"B_UGV_01_rcws_F",
"I_UGV_01_F",
"I_UGV_01_rcws_F",
"O_UGV_01_F",
"O_UGV_01_rcws_F",
"B_CTRG_LSV_01_light_F",
"B_T_LSV_01_unarmed_F",
"B_T_LSV_01_armed_F",
"B_T_LSV_01_AT_F",
"O_T_LSV_02_unarmed_F",
"O_T_LSV_02_armed_F",
"O_T_LSV_02_AT_F",
"B_MRAP_01_F",
"B_MRAP_01_hmg_F",
"B_MRAP_01_gmg_F",
"O_MRAP_02_F",
"O_MRAP_02_hmg_F",
"O_MRAP_02_gmg_F",
"I_MRAP_03_F",
"I_MRAP_03_hmg_F",
"I_MRAP_03_gmg_F",
"O_APC_Wheeled_02_rcws_v2_F",
"B_APC_Wheeled_01_cannon_F",
"I_APC_Wheeled_03_cannon_F",
"B_AFV_Wheeled_01_cannon_F",
"B_AFV_Wheeled_01_up_cannon_F", 
"I_LT_01_scout_F",
"I_LT_01_cannon_F",
"I_LT_01_AT_F",
"I_LT_01_AA_F",
"B_APC_Tracked_01_CRV_F",
"B_APC_Tracked_01_rcws_F",
"I_APC_tracked_03_cannon_F",
"O_APC_Tracked_02_cannon_F",
"B_APC_Tracked_01_AA_F",
"O_APC_Tracked_02_AA_F",
"B_MBT_01_cannon_F",
"B_MBT_01_TUSK_F",
"O_MBT_02_cannon_F", 
"I_MBT_03_cannon_F",
"O_MBT_04_cannon_F",
"O_MBT_04_command_F",
"LT_01_base_F",
"Boat_Armed_01_base_F"
];

/**
 * List of class names of HEAVY vehicles which can tow heavy towables objects. Takes precedence over R3F_LOG_CFG_remorqueurs
 */
R3F_LOG_CFG_remorqueursH =
[
	"Tractor_01_base_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Truck_03_base_F",
	"Wheeled_APC_F",
	"APC_Tracked_01_base_F",
	"APC_Tracked_02_base_F",
	"APC_Tracked_03_base_F",
	"MBT_01_base_F",
	"MBT_02_base_F",
	"MBT_03_base_F",
	"MBT_04_base_F"
];

R3F_LOG_CFG_remorqueurs append R3F_LOG_CFG_remorqueursH;

/**
 * List of class names of towables objects.
 */
R3F_LOG_CFG_objets_remorquables =
[
	"Car_F",
	"Ship_F",
"O_UAV_01_F",
"I_UAV_01_F",
"B_UAV_06_F",
"O_UAV_06_F",
"I_UAV_06_F",
"B_UAV_06_medical_F",
"O_UAV_06_medical_F",
"I_UAV_06_medical_F",
"C_IDAP_UAV_06_antimine_F",
"C_Heli_Light_01_civil_F",
"B_Heli_Light_01_F",
"O_Heli_Light_02_unarmed_F",
"I_Heli_light_03_unarmed_F",
"I_Heli_Transport_02_F",
"O_Heli_Transport_04_ammo_F",
"O_Heli_Transport_04_F",
"O_Heli_Transport_04_box_F",
"O_Heli_Transport_04_fuel_F",
"O_Heli_Transport_04_bench_F", 
"O_Heli_Transport_04_covered_F",
"O_Heli_Transport_04_medevac_F",
"O_Heli_Transport_04_repair_F",
"B_Heli_Transport_03_unarmed_F",
"B_Heli_Transport_03_F",
"B_Heli_Transport_01_F",
"B_Heli_Light_01_dynamicLoadout_F",
"O_Heli_Light_02_dynamicLoadout_F", 
"I_Heli_light_03_dynamicLoadout_F",
"B_Heli_Attack_01_dynamicLoadout_F",
"O_Heli_Attack_02_dynamicLoadout_F",
"B_T_UAV_03_F",
"C_Plane_Civil_01_F",
"I_Plane_Fighter_03_dynamicLoadout_F",
"I_Plane_Fighter_04_F",
"B_Plane_Fighter_01_Stealth_F",
"B_Plane_Fighter_01_F",
"O_Plane_Fighter_02_Stealth_F",
"B_Plane_CAS_01_dynamicLoadout_F",
"B_T_VTOL_01_infantry_F",
"O_T_VTOL_02_infantry_dynamicLoadout_F",
"O_T_UAV_04_CAS_F",
"B_UAV_02_dynamicLoadout_F",
"O_UAV_02_dynamicLoadout_F",
"B_UAV_05_F"
];

/**
 * List of class names of HEAVY towables objects. Takes precedence over R3F_LOG_CFG_objets_remorquables
 */
R3F_LOG_CFG_objets_remorquablesH =
[
	"Tractor_01_base_F",
	"Wheeled_APC_F",
	"APC_Tracked_01_base_F",
	"APC_Tracked_02_base_F",
	"APC_Tracked_03_base_F",
	"MBT_01_base_F",
	"MBT_02_base_F",
	"MBT_03_base_F",
	"MBT_04_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Transport_01_base_F",
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"VTOL_base_F",
	"UAV_05_Base_F",
	"Plane_Fighter_01_Base_F",
	"Plane_Fighter_02_Base_F",
	"Plane_CAS_01_base_F",
	"Plane_CAS_02_base_F"
];

R3F_LOG_CFG_objets_remorquables append R3F_LOG_CFG_objets_remorquablesH;

/****** LIFT WITH VEHICLE  ******/
/**
 * List of class names of air vehicles which can lift liftables objects.
 */
R3F_LOG_CFG_heliporteurs =
[
	"Helicopter_Base_F",
	"Heli_Light_01_base_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"Heli_Attack_01_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Transport_01_base_F",
	"VTOL_base_F"
];

/**
 * List of class names of HEAVY air vehicles which can lift heavy liftables objects. Takes precedence over R3F_LOG_CFG_objets_remorquables
 */
R3F_LOG_CFG_heliporteursH =
[
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F"
];

R3F_LOG_CFG_heliporteurs append R3F_LOG_CFG_heliporteursH;

/**
 * List of class names of liftables objects.
 */
R3F_LOG_CFG_objets_heliportables =
[
"C_Kart_01_F",
"C_Tractor_01_F",
"I_G_Quadbike_01_F",
"C_Hatchback_01_sport_F",
"C_SUV_01_F",
"C_Offroad_02_unarmed_F",
"C_Offroad_01_F",
"I_G_Offroad_01_F",
"B_GEN_Offroad_01_gen_F",
"C_Van_01_transport_F",
"C_Van_01_fuel_F",
"C_Van_02_vehicle_F",
"C_Van_02_transport_F",
"B_GEN_Van_02_transport_F",
"C_Van_02_service_F",
"O_Truck_03_device_F",
"O_Truck_03_medical_F",
"O_Truck_03_repair_F",
"I_Truck_02_ammo_F",
"I_Truck_02_medical_F",
"B_UGV_01_F",
"B_UGV_01_rcws_F",
"I_UGV_01_F",
"I_UGV_01_rcws_F",
"O_UGV_01_F",
"O_UGV_01_rcws_F",
"B_CTRG_LSV_01_light_F",
"B_T_LSV_01_unarmed_F",
"B_T_LSV_01_armed_F",
"B_T_LSV_01_AT_F",
"O_T_LSV_02_unarmed_F",
"O_T_LSV_02_armed_F",
"O_T_LSV_02_AT_F",
"B_MRAP_01_F",
"B_MRAP_01_hmg_F",
"B_MRAP_01_gmg_F",
"O_MRAP_02_F",
"O_MRAP_02_hmg_F",
"O_MRAP_02_gmg_F",
"I_MRAP_03_F",
"I_MRAP_03_hmg_F",
"I_MRAP_03_gmg_F",
"O_APC_Wheeled_02_rcws_v2_F",
"B_APC_Wheeled_01_cannon_F",
"I_APC_Wheeled_03_cannon_F",
"B_AFV_Wheeled_01_cannon_F",
"B_AFV_Wheeled_01_up_cannon_F", 
"I_LT_01_scout_F",
"I_LT_01_cannon_F",
"I_LT_01_AT_F",
"I_LT_01_AA_F",
"B_APC_Tracked_01_CRV_F",
"B_APC_Tracked_01_rcws_F",
"I_APC_tracked_03_cannon_F",
"O_APC_Tracked_02_cannon_F",
"B_APC_Tracked_01_AA_F",
"O_APC_Tracked_02_AA_F",
"B_MBT_01_cannon_F",
"B_MBT_01_TUSK_F",
"O_MBT_02_cannon_F", 
"I_MBT_03_cannon_F",
"O_MBT_04_cannon_F",
"O_MBT_04_command_F"

];

/**
 * List of class names of HEAVY liftables objects. Takes precedence over R3F_LOG_CFG_objets_heliportables
 */
R3F_LOG_CFG_objets_heliportablesH =
[
	"Tractor_01_base_F",
	"Wheeled_APC_F",
	"APC_Tracked_01_base_F",
	"APC_Tracked_02_base_F",
	"APC_Tracked_03_base_F",
	"MBT_01_base_F",
	"MBT_02_base_F",
	"MBT_03_base_F",
	"MBT_04_base_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"Heli_Attack_01_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Transport_01_base_F",
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"Plane_CAS_01_base_F",
	"Plane_CAS_02_base_F",
	"Plane_Fighter_03_base_F",
	"VTOL_01_base_F",
	"VTOL_02_base_F"
];

R3F_LOG_CFG_objets_heliportables append R3F_LOG_CFG_objets_heliportablesH;


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/


/**
 * List of class names of (ground or air) vehicles which can transport transportables objects.
 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
 */
R3F_LOG_CFG_transporteurs =
[
	["Quadbike_01_base_F", 5],
	["UGV_01_base_F", 10],
	["Hatchback_01_base_F", 10],
	["SUV_01_base_F", 20],
	["Offroad_01_base_F", 30],
	["Offroad_02_base_F", 20],
	["Van_01_base_F", 40],
	["Van_02_base_F", 50],
	["LSV_01_base_F", 15],
	["LSV_02_base_F", 15],
	["MRAP_01_base_F", 20],
	["MRAP_02_base_F", 20],
	["MRAP_03_base_F", 20],
	["Tractor_01_base_F", 20],
	["B_Truck_01_box_F", 150],
	["Truck_F", 75],
	["Wheeled_APC_F", 30],
	["UGV_02_Base_F", 3],
	["LT_01_base_F", 10],
	["Tank_F", 30],
	["Scooter_Transport_01_base_F", 5],
	["SDV_01_base_F", 10],
	["Rubber_duck_base_F", 10],
	["Boat_Civil_01_base_F", 10],
	["Boat_Transport_02_base_F", 15],
	["Boat_Armed_01_base_F", 20],
	["Heli_Light_01_base_F", 10],
	["Heli_Light_02_base_F", 20],
	["Heli_light_03_base_F", 20],
	["Heli_Transport_01_base_F", 25],
	["Heli_Transport_02_base_F", 30],
	["Heli_Transport_03_base_F", 30],
	["Heli_Transport_04_base_F", 30],
	["Heli_Attack_01_base_F", 10],
	["Heli_Attack_02_base_F", 20],
	["Plane_Civil_01_base_F", 5],
	["VTOL_01_base_F", 50],
	["VTOL_02_base_F", 30]
];


R3F_LOG_CFG_objets_transportables =
[
	["Static_Designator_01_base_F", 2],
	["Static_Designator_02_base_F", 2],
	["StaticWeapon", 5],
	["Box_NATO_AmmoVeh_F", 10],
	["B_supplyCrate_F", 5],
	["ReammoBox_F", 3],
	["Kart_01_Base_F", 5],
	["Quadbike_01_base_F", 10],
	["Rubber_duck_base_F", 10],
	["UAV_01_base_F", 2],
	["UAV_06_base_F", 2],
	["UGV_02_Base_F", 2],
	["Land_PierLadder_F", 3],
	["Land_BagBunker_Large_F", 10],
	["Land_BagBunker_Small_F", 5],
	["Land_BagBunker_Tower_F", 7],
	["Land_BagFence_Corner_F", 2],
	["Land_BagFence_End_F", 2],
	["Land_BagFence_Long_F", 3],
	["Land_BagFence_Round_F", 2],
	["Land_BagFence_Short_F", 2],
	["Land_BarGate_F", 3],
	["Land_Canal_WallSmall_10m_F", 4],
	["Land_Canal_Wall_Stairs_F", 3],
	["Land_CargoBox_V1_F", 5],
	["Land_Cargo_Patrol_V1_F", 7],
	["Land_Cargo_Tower_V1_F", 30],
	["Land_CncBarrier_F", 4],
	["Land_CncBarrierMedium_F", 4],
	["Land_CncBarrierMedium4_F", 4],
	["Land_CncShelter_F", 2],
	["Land_CncWall1_F", 3],
	["Land_CncWall4_F", 5],
	["Land_Crash_barrier_F", 5],
	["Land_HBarrierBig_F", 5],
	["Land_HBarrierTower_F", 8],
	["Land_HBarrierWall4_F", 4],
	["Land_HBarrierWall6_F", 6],
	["Land_HBarrier_1_F", 3],
	["Land_HBarrier_3_F", 4],
	["Land_HBarrier_5_F", 5],
	["Land_LampHarbour_F", 2],
	["Land_LampShabby_F", 2],
	["Land_MetalBarrel_F", 2],
	["Land_Mil_ConcreteWall_F", 5],
	["Land_Mil_WallBig_4m_F", 5],
	["Land_Obstacle_Ramp_F", 5],
	["Land_Pipes_large_F", 5],
	["Land_RampConcreteHigh_F", 6],
	["Land_RampConcrete_F", 5],
	["Land_Razorwire_F", 5],
	["Land_Sacks_goods_F", 2],
	["Land_Scaffolding_F", 5],
	["Land_Shoot_House_Wall_F", 3],
	["Land_Stone_8m_F", 5],
	["Land_ToiletBox_F", 2],
	["Land_BarrelWater_F", 2]

];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

R3F_LOG_CFG_objets_deplacables =
[
	"StaticWeapon",
	"ReammoBox_F",
	"Kart_01_Base_F",
	"Quadbike_01_base_F",
	"Rubber_duck_base_F",
	"SDV_01_base_F",
	"UAV_01_base_F",
	"UAV_06_base_F",
	"UGV_02_Base_F",
	"Land_PierLadder_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Tower_F",
	"Land_BagFence_Corner_F",
	"Land_BagFence_End_F",
	"Land_BagFence_Long_F",
	"Land_BagFence_Round_F",
	"Land_BagFence_Short_F",
	"Land_BarGate_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_CargoBox_V1_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_Cargo_Tower_V1_F",
	"Land_CncBarrier_F",
	"Land_CncBarrierMedium_F",
	"Land_CncBarrierMedium4_F",
	"Land_CncShelter_F",
	"Land_CncWall1_F",
	"Land_CncWall4_F",
	"Land_Crash_barrier_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierTower_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall6_F",
	"Land_HBarrier_1_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_LampHarbour_F",
	"Land_LampShabby_F",
	"Land_MetalBarrel_F",
	"Land_Mil_ConcreteWall_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Obstacle_Ramp_F",
	"Land_Pipes_large_F",
	"Land_RampConcreteHigh_F",
	"Land_RampConcrete_F",
	"Land_Razorwire_F",
	"Land_Sacks_goods_F",
	"Land_Scaffolding_F",
	"Land_Shoot_House_Wall_F",
	"Land_Stone_8m_F",
	"Land_ToiletBox_F",
	"Land_BarrelWater_F",
	"Land_BarGate_F",
	"Land_Loudspeakers_F",
	"Land_Timbers_F",
	"Land_TreeBin_F",
	"Land_Water_source_F",
	"Land_AncientPillar_F",
	"Land_AncientPillar_damaged_F",
	"Land_AncientPillar_fallen_F",
	"Land_BellTower_01_V1_F",
	"Land_BellTower_01_V2_F",
	"Land_Calvary_01_V1_F",
	"Land_Chapel_V1_F",
	"Land_Chapel_V2_F",
	"Land_Chapel_Small_V1_F",
	"Land_Bricks_V1_F",
	"Land_Bricks_V2_F", 
	"Land_CinderBlocks_F",
	"Land_Coil_F",
	"Land_ConcretePipe_F",
	"Land_Pallet_F",
	"Land_Pallet_vertical_F",
	"Land_WheelCart_F",
	"Land_WoodenBox_F",
	"Land_WorkStand_F",
	"Land_Grave_memorial_F",
	"Land_Grave_monument_F",
	"Land_Grave_obelisk_F",
	"Land_Grave_V1_F",
	"Land_LampAirport_off_F",
	"Land_LampDecor_off_F",
	"Land_LampDecor_F",
	"Land_LampSolar_F",
	"Land_MarketShelter_F",
	"Land_StallWater_F",
	"Land_Offices_01_V1_F", 
	"Land_Pavement_narrow_corner_F",
	"Land_Pavement_narrow_F",
	"Land_Pavement_wide_corner_F",
	"Land_Pavement_wide_F",
	"Land_Slide_F",
	"Land_BC_Basket_F",
	"Land_BC_Court_F",
	"Land_Goal_F",
	"Land_Tribune_F",
	"Land_Maroula_base_F",
	"Land_Maroula_F",
	"Land_MolonLabe_F",
	"Land_Amphitheater_F",
	"Land_Castle_01_tower_F",
	"Land_Church_01_V1_F",
	"Land_LightHouse_F",
	"Land_Lighthouse_small_F",
	"Land_WIP_F",
	"Land_u_Addon_02_V1_F",
	"Land_i_Addon_04_V1_F",
	"Land_i_Shop_01_V1_F",
	"Land_i_House_Small_03_V1_F",
	"Land_Airport_Tower_F",
	"Land_Hangar_F",
	"Land_CarService_F",  
	"Land_Crane_F",
	"Land_Factory_Conv2_F",
	"Land_fs_sign_F",
	"Land_fs_price_F",
	"Land_IndPipe1_20m_F",
	"Land_IndPipe1_90degL_F",
	"Land_IndPipe1_90degR_F",
	"Land_IndPipe1_ground_F",
	"Land_IndPipe1_Uup_F",
	"Land_IndPipe1_valve_F",
	"Land_HighVoltageTower_F",
	"Land_SolarPanel_3_F",
	"Land_spp_Panel_F",
	"Land_i_Barracks_V1_F",
	"Land_Bunker_F",
	"Land_Cargo_House_V1_F",
	"Land_Cargo_Patrol_V3_F",
	"Land_Medevac_house_V1_F",
	"Land_HBarrierWall_corner_F",
	"Land_HBarrierWall_corridor_F",
	"Land_MilOffices_V1_F",
	"Land_Radar_F",
	"CamoNet_BLUFOR_F",
	"Land_TentHangar_V1_F",
	"Land_Pier_Box_F",
	"Land_Sea_Wall_F",
	"Land_Research_house_V1_F",
	"BlockConcrete_F",
	"Land_Shoot_House_Wall_Long_F",
	"Land_Shoot_House_Panels_Prone_F",
	"Land_Shoot_House_Tunnel_F",
	"Land_Canal_Wall_10m_F",
	"Land_City_Gate_F",
	"Land_CncBarrier_stripes_F",
	"Land_PhoneBooth_01_F",
	"Land_Grave_rocks_F",
	"Land_SlideCastle_F",
	"Land_Atm_01_F",
	"Land_Kiosk_gyros_F",
	"Land_Carousel_01_F",
	"Land_Swing_01_F",
	"Land_IRMaskingCover_01_F",
	"Land_ClothesLine_01_full_F",
	"Land_FireEscape_01_short_F",
	"Land_GarbageBin_02_F",
	"Land_PicnicTable_01_F",
	"Land_Pot_01_F",
	"Land_House_Big_03_F",
	"Land_FuelStation_01_arrow_F",
	"Land_SignMonolith_01_F",
	"Land_Hotel_01_F",
	"Land_MultistoryBuilding_03_F",
	"Land_AncientStatue_01_F",
	"Land_AncientStatue_02_F",
	"Land_StoneTanoa_01_F",
	"Land_RaiStone_01_F",
	"Land_BasaltKerb_01_pile_F",
	"Land_BasaltKerb_01_4m_F",
	"Land_BasaltKerb_01_2m_d_F",
	"Land_Cathedral_01_F",
	"Land_Fortress_01_cannon_F",
	"Land_ContainerLine_01_F",
	"Land_MobileCrane_01_F",
	"Land_SCF_01_chimney_F",
	"Land_Airport_01_controlTower_F",
	"Land_Track_01_3m_F",
	"Land_Track_01_7deg_F",
	"Land_Track_01_10m_F",
	"Land_Track_01_15deg_F",
	"Land_Track_01_20m_F",
	"Land_Track_01_30deg_F",
	"Land_Track_01_bridge_F",
	"Land_Track_01_bumper_F",
	"Land_Track_01_crossing_F",
	"Land_Track_01_switch_F",
	"Land_Track_01_turnout_left_F",
	"Land_Track_01_turnout_right_F",
	"Land_EmplacementGun_01_mossy_F",
	"Land_EmplacementGun_01_d_mossy_F",
	"Land_BagBunker_01_large_green_F",
	"Land_BagFence_01_corner_green_F",
	"Land_BagFence_01_end_green_F",
	"Land_BagFence_01_long_green_F",
	"Land_BagFence_01_round_green_F",
	"Land_HBarrier_01_big_4_green_F",
	"Land_HBarrier_01_big_tower_green_F",
	"Land_HBarrier_01_line_1_green_F",
	"Land_HBarrier_01_line_3_green_F",
	"Land_HBarrier_01_line_5_green_F",
	"Land_HBarrier_01_tower_green_F",
	"Land_HBarrier_01_wall_4_green_F",
	"Land_HBarrier_01_wall_6_green_F",
	"Land_HBarrier_01_wall_corner_green_F",
	"Land_HBarrier_01_wall_corridor_green_F",
	"Land_PillboxBunker_01_big_F",
	"Land_PillboxBunker_01_hex_F",
	"Land_PillboxBunker_01_rectangle_F",
	"Land_PillboxWall_01_3m_F",
	"Land_PillboxWall_01_3m_round_F",
	"Land_PillboxWall_01_6m_F",
	"Land_PillboxWall_01_6m_round_F",
	"Land_TrenchFrame_01_F",
	"Land_BambooFence_01_s_4m_F",
	"Land_Hedge_01_s_2m_F",
	"Land_Hedge_01_s_4m_F",
	"Land_GuardRailing_01_F",
	"Land_WoodenWall_02_s_4m_F",
	"Land_CzechHedgehog_01_new_F",
	"Land_ConcreteHedgehog_01_palette_F",
	"Land_Destroyer_01_Boat_Rack_01_F",
	"Land_Graffiti_01_F",
	"Land_Graffiti_03_F",
	"Land_GarbageContainer_closed_F",
	"Land_Football_01_F",
	"Land_GarbageBarrel_01_english_F",
	"Land_VR_Slope_01_F"
];
